services:
  db:
    ports: !override
      - "127.0.0.1:5432:5432"

  backend:
    ports: !override
      - "127.0.0.1:8080:${SERVER_PORT}"

  frontend:
    ports: !override
      - "127.0.0.1:3000:80"
